name = "backend"
compatibility_date = "2025-07-18"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza181UTRtQlBnVG54UEtYbi1xTzl1M0kiLCJhcGlfa2V5IjoiMDFLMk03OVRORUNLN0FZU0JZQ0c2V0VKS0siLCJ0ZW5hbnRfaWQiOiJmN2Q4ZGE3YzE5YzlmYTFiYmMxNGI4NjE1MTUyMDY5NzAyNTI0ZDQ2MDJlOWNhOTFkNzlmZjM2NjU1NWJmNjQ0IiwiaW50ZXJuYWxfc2VjcmV0IjoiODQxZWE3ZTgtYzljMS00ODUwLThjZDAtYjU1YTBiYjM5NDlhIn0.5l2VTOyXHxeM6juV12xD6-hwmRttcTwM75ouAQLxI2Q"
JWT_SECRET = "asfasdjfoa"

